# Generated by Django 5.2.6 on 2026-06-16 17:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_user_type_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=50)),
                ('room_name', models.CharField(max_length=100)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_occupants', models.PositiveIntegerField(default=1)),
                ('default_rent', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('room_image', models.ImageField(blank=True, null=True, upload_to='rentease/rooms/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'phong',
                'ordering': ['owner', 'room_code'],
                'indexes': [models.Index(fields=['status'], name='phong_status_ea1911_idx'), models.Index(fields=['room_code'], name='phong_room_co_405c26_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'room_code'), name='unique_room_code_per_owner')],
            },
        ),
    ]
