# Generated by Django 5.2.6 on 2026-06-16 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_map_legacy_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(user_type='warden').update(user_type='OWNER')
    User.objects.filter(user_type='student').update(user_type='TENANT')


def backwards_map_legacy_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(user_type='OWNER').update(user_type='warden')
    User.objects.filter(user_type='TENANT').update(user_type='student')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('TENANT', 'Tenant')], default='TENANT', max_length=20),
        ),
        migrations.RunPython(forwards_map_legacy_roles, backwards_map_legacy_roles),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='rentease/avatars/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('rental_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rentease_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Owner Profile',
                'verbose_name_plural': 'Owner Profiles',
                'db_table': 'nguoi_dung',
                'indexes': [models.Index(fields=['phone_number'], name='nguoi_dung_phone_n_a8903d_idx')],
            },
        ),
    ]
