# Generated by Django 5.2.6 on 2026-07-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotenant',
            options={'ordering': ['full_name'], 'verbose_name': 'Người ở cùng', 'verbose_name_plural': 'Người ở cùng'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['full_name'], 'verbose_name': 'Khách thuê', 'verbose_name_plural': 'Khách thuê'},
        ),
        migrations.AlterField(
            model_name='tenant',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Đang thuê'), ('inactive', 'Ngừng thuê'), ('blocked', 'Đã khóa')], default='active', max_length=20),
        ),
    ]
