name: rentease-management

services:
  db:
    image: postgres:15-alpine
    container_name: rentease-management-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rentease_db
      POSTGRES_USER: rentease_user
      POSTGRES_PASSWORD: rentease_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: rentease-management-postgres-data
