# Generated by Django 5.2.6 on 2026-06-16 18:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_code', models.CharField(blank=True, max_length=80, unique=True)),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('issued_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'hoa_don',
                'ordering': ['-year', '-month', 'contract__contract_code'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_start', models.PositiveIntegerField()),
                ('electricity_end', models.PositiveIntegerField()),
                ('electricity_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('water_start', models.PositiveIntegerField()),
                ('water_end', models.PositiveIntegerField()),
                ('water_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('electricity_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('water_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('rent_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('service_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Detail',
                'verbose_name_plural': 'Invoice Details',
                'db_table': 'chi_tiet_hoa_don',
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('e_wallet', 'E-Wallet'), ('other', 'Other')], default='cash', max_length=30)),
                ('transaction_code', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
                'db_table': 'lich_su_thanh_toan',
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('electricity_unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('water_unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_configs', to='properties.room')),
            ],
            options={
                'verbose_name': 'Price Config',
                'verbose_name_plural': 'Price Configs',
                'db_table': 'cau_hinh_gia',
                'ordering': ['-year', '-month', 'room__room_code'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='hoa_don_status_cd7b95_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['year', 'month'], name='hoa_don_year_08b53a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='hoa_don_due_dat_a647ea_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['contract'], name='hoa_don_contrac_14f34f_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('contract', 'month', 'year'), name='unique_invoice_per_contract_month'),
        ),
        migrations.AddIndex(
            model_name='invoicedetail',
            index=models.Index(fields=['invoice'], name='chi_tiet_ho_invoice_d7dddf_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['invoice'], name='lich_su_tha_invoice_0d97e5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['paid_at'], name='lich_su_tha_paid_at_567b33_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['method'], name='lich_su_tha_method_d5b317_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['transaction_code'], name='lich_su_tha_transac_4f927a_idx'),
        ),
        migrations.AddIndex(
            model_name='priceconfig',
            index=models.Index(fields=['room'], name='cau_hinh_gi_room_id_71dcec_idx'),
        ),
        migrations.AddIndex(
            model_name='priceconfig',
            index=models.Index(fields=['year', 'month'], name='cau_hinh_gi_year_bc4f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='priceconfig',
            index=models.Index(fields=['room', 'year', 'month'], name='cau_hinh_gi_room_id_a64221_idx'),
        ),
        migrations.AddConstraint(
            model_name='priceconfig',
            constraint=models.UniqueConstraint(fields=('room', 'month', 'year'), name='unique_price_config_per_room_month'),
        ),
    ]
