# Generated by Django 5.2.6 on 2026-06-30 16:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('properties', '0004_require_room_property_and_scope_room_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_code', models.CharField(max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('initial_value', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('retired_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='properties.room')),
            ],
            options={
                'verbose_name': 'Meter',
                'verbose_name_plural': 'Meters',
                'db_table': 'dong_ho',
                'ordering': ['room', 'meter_code'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('previous_value', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_value', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('consumption', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_meter_readings', to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='billing.meter')),
            ],
            options={
                'verbose_name': 'Meter Reading',
                'verbose_name_plural': 'Meter Readings',
                'db_table': 'chi_so_dong_ho',
                'ordering': ['-year', '-month', 'meter'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('charge_method', models.CharField(choices=[('fixed', 'Fixed'), ('usage', 'Usage-based')], max_length=20)),
                ('unit', models.CharField(max_length=30)),
                ('default_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_definitions', to='properties.property')),
            ],
            options={
                'verbose_name': 'Service Definition',
                'verbose_name_plural': 'Service Definitions',
                'db_table': 'dinh_nghia_dich_vu',
                'ordering': ['property', 'service_code'],
            },
        ),
        migrations.AddField(
            model_name='meter',
            name='service_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='billing.servicedefinition'),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_code', models.CharField(max_length=50)),
                ('line_type', models.CharField(choices=[('rent', 'Rent'), ('electricity', 'Electricity'), ('water', 'Water'), ('service', 'Service'), ('adjustment', 'Adjustment'), ('discount', 'Discount')], max_length=20)),
                ('direction', models.CharField(choices=[('charge', 'Charge'), ('credit', 'Credit')], default='charge', max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
                ('legacy_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compatibility_lines', to='billing.invoicedetail')),
                ('meter_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='billing.meterreading')),
                ('service_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='billing.servicedefinition')),
            ],
            options={
                'verbose_name': 'Invoice Line',
                'verbose_name_plural': 'Invoice Lines',
                'db_table': 'dong_hoa_don',
                'ordering': ['invoice', 'sort_order', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['year', 'month'], name='chi_so_dong_year_58ebe4_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['read_at'], name='chi_so_dong_read_at_0000a7_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['captured_by'], name='chi_so_dong_capture_4aff9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.UniqueConstraint(fields=('meter', 'month', 'year'), name='unique_meter_reading_period'),
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='meter_reading_month_valid'),
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.CheckConstraint(condition=models.Q(('year__gte', 2000)), name='meter_reading_year_valid'),
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.CheckConstraint(condition=models.Q(('previous_value__gte', 0)), name='meter_reading_previous_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.CheckConstraint(condition=models.Q(('current_value__gte', models.F('previous_value'))), name='meter_reading_current_not_decreasing'),
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.CheckConstraint(condition=models.Q(('consumption__gte', 0)), name='meter_reading_consumption_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='servicedefinition',
            index=models.Index(fields=['property', 'is_active'], name='dinh_nghia__propert_d38074_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedefinition',
            index=models.Index(fields=['charge_method'], name='dinh_nghia__charge__c3f446_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicedefinition',
            constraint=models.UniqueConstraint(fields=('property', 'service_code'), name='unique_service_code_per_property'),
        ),
        migrations.AddConstraint(
            model_name='servicedefinition',
            constraint=models.CheckConstraint(condition=models.Q(('default_unit_price__gte', 0)), name='service_default_price_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['room', 'is_active'], name='dong_ho_room_id_0de720_idx'),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['service_definition'], name='dong_ho_service_7c84ed_idx'),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['serial_number'], name='dong_ho_serial__13a59b_idx'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.UniqueConstraint(fields=('room', 'meter_code'), name='unique_meter_code_per_room'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.CheckConstraint(condition=models.Q(('initial_value__gte', 0)), name='meter_initial_value_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.CheckConstraint(condition=models.Q(('retired_on__isnull', True), ('installed_on__isnull', True), ('retired_on__gte', models.F('installed_on')), _connector='OR'), name='meter_retired_on_not_before_installed'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice', 'sort_order'], name='dong_hoa_do_invoice_05d70c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['line_type'], name='dong_hoa_do_line_ty_a5fba5_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['service_definition'], name='dong_hoa_do_service_3fc7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['meter_reading'], name='dong_hoa_do_meter_r_c3e4e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(fields=('invoice', 'line_code'), name='unique_line_code_per_invoice'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='invoice_line_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='invoice_line_unit_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='invoice_line_amount_nonnegative'),
        ),
    ]
