# Generated by Django 5.2.6 on 2026-07-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_paymentwebhookevent_paymentintent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-year', '-month', 'contract__contract_code'], 'verbose_name': 'Hóa đơn', 'verbose_name_plural': 'Hóa đơn'},
        ),
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'ordering': ['invoice', 'sort_order', 'pk'], 'verbose_name': 'Dòng hóa đơn', 'verbose_name_plural': 'Dòng hóa đơn'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Bản nháp'), ('unpaid', 'Chưa thanh toán'), ('partial', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('overdue', 'Quá hạn')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='direction',
            field=models.CharField(choices=[('charge', 'Khoản thu'), ('credit', 'Khoản giảm trừ')], default='charge', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='line_type',
            field=models.CharField(choices=[('rent', 'Tiền phòng'), ('electricity', 'Tiền điện'), ('water', 'Tiền nước'), ('service', 'Phí dịch vụ'), ('adjustment', 'Điều chỉnh'), ('discount', 'Giảm giá')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='method',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('bank_transfer', 'Chuyển khoản ngân hàng'), ('e_wallet', 'Ví điện tử'), ('other', 'Khác')], default='cash', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã hủy'), ('expired', 'Đã hết hạn'), ('failed', 'Thanh toán thất bại'), ('review', 'Cần kiểm tra')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicedefinition',
            name='charge_method',
            field=models.CharField(choices=[('fixed', 'Cố định'), ('usage', 'Theo mức sử dụng')], max_length=20),
        ),
    ]
