# Generated by Django 5.2.6 on 2026-07-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-start_date', 'contract_code'], 'verbose_name': 'Hợp đồng', 'verbose_name_plural': 'Hợp đồng'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_cycle',
            field=models.CharField(choices=[('monthly', 'Theo tháng'), ('yearly', 'Theo năm')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Bản nháp'), ('active', 'Đang hiệu lực'), ('expired', 'Đã hết hạn'), ('terminated', 'Đã chấm dứt')], default='draft', max_length=20),
        ),
    ]
