# Generated by Django 5.2.6 on 2026-07-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('properties', '0004_require_room_property_and_scope_room_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'ordering': ['-scheduled_for', '-created_at'], 'verbose_name': 'Maintenance Record', 'verbose_name_plural': 'Maintenance Records'},
        ),
        migrations.RemoveIndex(
            model_name='maintenancerecord',
            name='bao_tri_perform_331f65_idx',
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='scheduled_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='performed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['scheduled_for'], name='bao_tri_schedul_fa1475_idx'),
        ),
    ]
