# Generated by Django 5.2.6 on 2026-07-05 13:02

from django.db import migrations
import datetime

def backfill_dates(apps, schema_editor):
    MaintenanceRecord = apps.get_model('maintenance', 'MaintenanceRecord')
    for record in MaintenanceRecord.objects.all():
        if record.performed_date:
            record.scheduled_for = record.performed_date
            
            # Create a basic datetime at noon UTC for existing records' completed_at/started_at
            dt = datetime.datetime.combine(record.performed_date, datetime.time(12, 0), tzinfo=datetime.timezone.utc)
            
            if record.status == 'completed':
                record.completed_at = dt
                record.started_at = dt
            elif record.status == 'in_progress':
                record.started_at = dt
            
            record.save()

def revert_dates(apps, schema_editor):
    MaintenanceRecord = apps.get_model('maintenance', 'MaintenanceRecord')
    for record in MaintenanceRecord.objects.all():
        if record.scheduled_for:
            record.performed_date = record.scheduled_for
            record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenancerecord_options_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_dates, revert_dates),
    ]
