# Generated by Django 5.2.6 on 2026-07-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20260705_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'ordering': ['-scheduled_for', '-created_at'], 'verbose_name': 'Lịch bảo trì', 'verbose_name_plural': 'Lịch bảo trì'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Thông báo', 'verbose_name_plural': 'Thông báo'},
        ),
        migrations.AlterModelOptions(
            name='repairrequest',
            options={'ordering': ['-requested_at', '-created_at'], 'verbose_name': 'Yêu cầu sửa chữa', 'verbose_name_plural': 'Yêu cầu sửa chữa'},
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Đã lên lịch'), ('in_progress', 'Đang thực hiện'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'Thông báo chung'), ('invoice', 'Hóa đơn'), ('payment', 'Thanh toán'), ('overdue', 'Quá hạn'), ('repair', 'Sửa chữa'), ('maintenance', 'Bảo trì')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ'), ('in_progress', 'Đang xử lý'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
