# Generated by Django 5.2.6 on 2026-07-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_require_room_property_and_scope_room_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['owner', 'property_code'], 'verbose_name': 'Cơ sở cho thuê', 'verbose_name_plural': 'Cơ sở cho thuê'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['owner', 'room_code'], 'verbose_name': 'Phòng trọ', 'verbose_name_plural': 'Phòng trọ'},
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Ngừng hoạt động')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Còn trống'), ('occupied', 'Đã thuê'), ('maintenance', 'Đang bảo trì'), ('inactive', 'Ngừng sử dụng')], default='available', max_length=20),
        ),
    ]
