# Generated by Django 5.2.6 on 2026-06-16 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('citizen_id', models.CharField(blank=True, max_length=20)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_tenants', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Co-tenant',
                'verbose_name_plural': 'Co-tenants',
                'db_table': 'nguoi_o_cung',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['citizen_id'], name='nguoi_o_cun_citizen_104733_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('citizen_id', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('citizen_id_front', models.ImageField(blank=True, null=True, upload_to='rentease/citizen_ids/')),
                ('citizen_id_back', models.ImageField(blank=True, null=True, upload_to='rentease/citizen_ids/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'khach_thue',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['phone_number'], name='khach_thue_phone_n_4d52e7_idx'), models.Index(fields=['email'], name='khach_thue_email_295479_idx'), models.Index(fields=['status'], name='khach_thue_status_893bd3_idx')],
            },
        ),
    ]
