# Generated by Django 5.2.6 on 2026-07-05 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'gov_audit_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='gov_audit_e_content_794638_idx'), models.Index(fields=['action'], name='gov_audit_e_action_f07e2c_idx'), models.Index(fields=['actor'], name='gov_audit_e_actor_i_8e3c24_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrivateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('identity_card', 'Identity Card / Passport'), ('contract', 'Signed Contract'), ('maintenance_evidence', 'Maintenance Evidence')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('storage_key', models.CharField(help_text='Path or UUID to the private storage object', max_length=512)),
                ('retention_status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('marked_for_deletion', 'Marked for Deletion')], default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gov_private_document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='gov_private_content_8cdff0_idx'), models.Index(fields=['category'], name='gov_private_categor_e6d9e8_idx'), models.Index(fields=['retention_status'], name='gov_private_retenti_20901a_idx')],
            },
        ),
    ]
