# Generated by Django 5.2.6 on 2026-06-17 04:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('listing_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('hidden', 'Hidden'), ('rented', 'Rented'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('available_from', models.DateField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='properties.room')),
            ],
            options={
                'verbose_name': 'Room Listing',
                'verbose_name_plural': 'Room Listings',
                'db_table': 'tin_phong',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViewingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viewing_registrations', to='listings.roomlisting')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewing_registrations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Viewing Registration',
                'verbose_name_plural': 'Viewing Registrations',
                'db_table': 'dang_ky_xem_phong',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='roomlisting',
            index=models.Index(fields=['room'], name='tin_phong_room_id_15c829_idx'),
        ),
        migrations.AddIndex(
            model_name='roomlisting',
            index=models.Index(fields=['status'], name='tin_phong_status_e03acc_idx'),
        ),
        migrations.AddIndex(
            model_name='roomlisting',
            index=models.Index(fields=['available_from'], name='tin_phong_availab_79ab9f_idx'),
        ),
        migrations.AddIndex(
            model_name='roomlisting',
            index=models.Index(fields=['published_at'], name='tin_phong_publish_b01172_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingregistration',
            index=models.Index(fields=['listing'], name='dang_ky_xem_listing_792acb_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingregistration',
            index=models.Index(fields=['tenant'], name='dang_ky_xem_tenant__3e440b_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingregistration',
            index=models.Index(fields=['status'], name='dang_ky_xem_status_171ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingregistration',
            index=models.Index(fields=['preferred_date'], name='dang_ky_xem_preferr_7d93dd_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingregistration',
            index=models.Index(fields=['created_at'], name='dang_ky_xem_created_f20621_idx'),
        ),
    ]
