# Generated by Django 5.2.6 on 2026-07-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomlisting',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Tin đăng phòng', 'verbose_name_plural': 'Tin đăng phòng'},
        ),
        migrations.AlterModelOptions(
            name='viewingregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đăng ký xem phòng', 'verbose_name_plural': 'Đăng ký xem phòng'},
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='status',
            field=models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã đăng'), ('hidden', 'Đã ẩn'), ('rented', 'Đã thuê'), ('expired', 'Hết hạn')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='viewingregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ'), ('confirmed', 'Đã xác nhận'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy'), ('no_show', 'Không đến xem')], default='pending', max_length=20),
        ),
    ]
