# Generated by Django 5.2.6 on 2026-06-16 19:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='rentease/repair_requests/')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('owner_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_requests', to='properties.room')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_requests', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Repair Request',
                'verbose_name_plural': 'Repair Requests',
                'db_table': 'yeu_cau_sua_chua',
                'ordering': ['-requested_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('general', 'General'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('overdue', 'Overdue'), ('repair', 'Repair'), ('maintenance', 'Maintenance')], default='general', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='billing.invoice')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tenants.tenant')),
                ('repair_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='maintenance.repairrequest')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'thong_bao',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('vendor_name', models.CharField(blank=True, max_length=150)),
                ('performed_by', models.CharField(blank=True, max_length=150)),
                ('performed_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='properties.room')),
                ('repair_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='maintenance.repairrequest')),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'verbose_name_plural': 'Maintenance Records',
                'db_table': 'bao_tri',
                'ordering': ['-performed_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='repairrequest',
            index=models.Index(fields=['status'], name='yeu_cau_sua_status_862f34_idx'),
        ),
        migrations.AddIndex(
            model_name='repairrequest',
            index=models.Index(fields=['priority'], name='yeu_cau_sua_priorit_cf8d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='repairrequest',
            index=models.Index(fields=['requested_at'], name='yeu_cau_sua_request_c355aa_idx'),
        ),
        migrations.AddIndex(
            model_name='repairrequest',
            index=models.Index(fields=['room'], name='yeu_cau_sua_room_id_c7f7e8_idx'),
        ),
        migrations.AddIndex(
            model_name='repairrequest',
            index=models.Index(fields=['tenant'], name='yeu_cau_sua_tenant__0aa25e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant'], name='thong_bao_tenant__c04734_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['invoice'], name='thong_bao_invoice_124249_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['repair_request'], name='thong_bao_repair__2b0817_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='thong_bao_notific_a6f8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='thong_bao_is_read_0b6f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='thong_bao_created_d43a96_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['status'], name='bao_tri_status_47a57c_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['maintenance_type'], name='bao_tri_mainten_aa7866_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['performed_date'], name='bao_tri_perform_331f65_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['room'], name='bao_tri_room_id_8d0006_idx'),
        ),
    ]
